image: docker:24.0.5
services:
  - docker:24.0.5-dind

variables:
  DOCKER_DRIVER: overlay2
  # Nom de l'image dans le registre GitLab
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

stages:
  - test
  - build_push

# Job 1 : Tests unitaires (Maven pur)
unit_tests:
  image: maven:3.9-eclipse-temurin-17
  stage: test
  script:
    # On doit réinstaller la lib ici aussi car c'est un conteneur vierge
    - mvn install:install-file -Dfile=TarsosDSP-2.4.jar -DgroupId=be.tarsos.dsp -DartifactId=core -Dversion=2.5 -Dpackaging=jar
    - mvn test
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml

# Job 2 : Construction et Envoi Docker
docker_build:
  stage: build_push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main
    - master
    - develop