version: '3.8'

services:
  server-analyse:
    build: .
    container_name: samsoul-analyse
    ports:
      - "65432:65432"
    environment:
      - CENTRAL_HOST=server-central
      - CENTRAL_PORT=9999
    depends_on:
      - server-central
    networks:
      - samsoul-network

  # --- Serveur Central Java (Simulé car pas encore relié) ---
  server-central:
    image: eclipse-temurin:17-jre-alpine # placeholder
    container_name: samsoul-central
    ports:
      - "9999:9999"
    networks:
      - samsoul-network

  # --- BDD MongoDB ---
  mongo:
    image: mongo:6.0
    container_name: samsoul-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - samsoul-network

networks:
  samsoul-network:
    driver: bridge

volumes:
  mongo-data: